name:                 course-design
version:              0.1.0.0
visibility:           public
id:                   course-design-0.1.0.0-inplace
key:                  course-design-0.1.0.0-inplace
license:              MIT
maintainer:           kfove.liang@protonmail.com
author:               luckycyang
abi:                  inplace
exposed:              True
exposed-modules:      MyLib
import-dirs:
    /home/cyang/Public/GitCell/course_design/dist-newstyle/build/x86_64-linux/ghc-9.8.4/course-design-0.1.0.0/build

library-dirs:
    /home/cyang/Public/GitCell/course_design/dist-newstyle/build/x86_64-linux/ghc-9.8.4/course-design-0.1.0.0/build

library-dirs-static:
    /home/cyang/Public/GitCell/course_design/dist-newstyle/build/x86_64-linux/ghc-9.8.4/course-design-0.1.0.0/build

dynamic-library-dirs:
    /home/cyang/Public/GitCell/course_design/dist-newstyle/build/x86_64-linux/ghc-9.8.4/course-design-0.1.0.0/build

data-dir:             /home/cyang/Public/GitCell/course_design/.
hs-libraries:         HScourse-design-0.1.0.0-inplace
depends:              base-4.19.2.0-213b
haddock-interfaces:
    /home/cyang/Public/GitCell/course_design/dist-newstyle/build/x86_64-linux/ghc-9.8.4/course-design-0.1.0.0/doc/html/course-design/course-design.haddock

haddock-html:
    /home/cyang/Public/GitCell/course_design/dist-newstyle/build/x86_64-linux/ghc-9.8.4/course-design-0.1.0.0/doc/html/course-design
